---
name: PLCComS
version: 1.0.7
slug: plccoms
description: Tecomat PLC communication server
url: https://github.com/petrzoufaly/ha-addon-plccoms
init: false
arch:
  - aarch64
  - amd64
startup: services
ports:
  5011/tcp: 5011
